apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: "redis-server"
  selector:
    app: redis
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  ports:
  - port: 6379
    targetPort: "redis-server"
  selector:
    app: redis
    role: slave
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-ha
spec:
  replicas: 3
  template:
    metadata:
      labels:
       app: redis
    spec:
      containers:
      - name: redis
        imagePullPolicy: Never
        image: core/redis
        args:
          - --topology
          - leader
          - --group
          - redis-cluster-test
          - --peer
          - hab-bootstrap.default.svc.cluster.local
          - --listen-gossip
          - $(POD_IP)
        env:
          - name: HAB_REDIS
            value: 'protected-mode="no"'
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
          - name: "redis-server"
            containerPort: 6379
      - name: redis-publisher
        imagePullPolicy: Never
        image: moretea/redis-publisher
        args:
          - --group
          - redis-cluster-publisher
          - --peer
          - hab-bootstrap.default.svc.cluster.local
          - --listen-gossip
          - $(POD_IP):9639
          - --listen-http
          - $(POD_IP):9632
          - --bind
          - redis:redis.redis-cluster-test
        env:
          - name: HAB_REDIS
            value: 'protected-mode="no"'
#          - name: RUST_LOG
#            value: debug
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
          - name: "redis-server"
            containerPort: 6379
