apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: leader
spec:
  ports:
  - port: 6379
    targetPort: "redis-server"
  selector:
    app: redis
    role: leader 
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: follower
spec:
  ports:
  - port: 6379
    targetPort: "redis-server"
  selector:
    app: redis
    role: follower
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-ha
spec:
  replicas: 5
  template:
    metadata:
      labels:
       app: redis
    spec:
      containers:
      - name: redis
        imagePullPolicy: Never
        image: core/redis
        args:
          - --topology
          - leader
          - --group
          - redis-cluster-test
          - --peer
          - hab-bootstrap.default.svc.cluster.local
          - --listen-gossip
          - $(POD_IP)
        env:
          - name: HAB_REDIS
            value: 'protected-mode="no"'
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        ports:
          - name: "redis-server"
            containerPort: 6379
        ports:
          - name: "redis-server"
            containerPort: 6379
      - name: redis-publisher
        imagePullPolicy: Never
        image: alpine-sidekick
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
